import { WeddingDayTimelineItem } from './client-helpers';

export const categoryLabels: Record<NonNullable<WeddingDayTimelineItem['category']>, string> = {
  preparation: 'Préparatifs',
  mairie: 'Mairie',
  eglise: 'Église',
  vindhonneur: "Vin d'honneur",
  repas: 'Dîner / Repas',
  bal: 'Soirée / Bal',
  autre: 'Autre',
};

export const categoryOrder: NonNullable<WeddingDayTimelineItem['category']>[] = [
  'preparation',
  'mairie',
  'eglise',
  'vindhonneur',
  'repas',
  'bal',
  'autre',
];

export const DEFAULT_TEMPLATES: WeddingDayTimelineItem[] = [
  // Préparatifs
  {
    time: '06:30',
    duration: '1 h 30',
    title: 'Petit-déjeuner des mariés',
    who: 'Domaine',
    location: 'Suite nuptiale',
    note: 'Prévoir le plateau la veille au soir.',
    category: 'preparation',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '08:00',
    duration: '2 h',
    title: 'Coiffure et maquillage',
    who: 'Mariam Beauty',
    location: 'Salon du premier étage',
    note: "La mariée en dernier, les témoins d'abord.",
    category: 'preparation',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '08:30',
    duration: '45 min',
    title: 'Livraison des fleurs',
    who: 'Fleurs de Ouidah',
    location: 'Entrée de service',
    category: 'preparation',
    visibleTo: 'vendors',
    highlight: false,
  },
  {
    time: '09:00',
    duration: '1 h',
    title: 'Arrivée photographe + vidéaste',
    who: 'Studio Lumen',
    location: 'Hôtel / domicile',
    note: 'Photos getting ready des deux côtés.',
    category: 'preparation',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '09:15',
    duration: '1 h',
    title: 'Montage de la arche',
    who: 'Fleurs de Ouidah',
    location: 'Jardin sud',
    category: 'preparation',
    visibleTo: 'vendors',
    highlight: false,
  },
  {
    time: '09:30',
    duration: '3 h',
    title: 'Dressage des tables',
    who: 'Domaine',
    location: 'Salle d\'honneur',
    note: 'Plan de table validé, n couverts.',
    category: 'preparation',
    visibleTo: 'vendors',
    highlight: false,
  },
  {
    time: '10:00',
    duration: '30 min',
    title: 'Arrivée du traiteur',
    who: 'Table Céleste',
    location: 'Cuisines',
    category: 'preparation',
    visibleTo: 'vendors',
    highlight: false,
  },
  {
    time: '11:00',
    duration: '1 h',
    title: 'Balance son et lumière',
    who: 'DJ Kévin',
    location: 'Salle d\'honneur',
    category: 'preparation',
    visibleTo: 'vendors',
    highlight: false,
  },
  {
    time: '12:00',
    duration: '45 min',
    title: 'Déjeuner léger de l\'équipe',
    who: 'Table Céleste',
    location: 'Office',
    category: 'preparation',
    visibleTo: 'vendors',
    highlight: false,
  },
  {
    time: '13:00',
    duration: '1 h',
    title: 'Habillage des mariés',
    who: 'Témoins',
    location: 'Suites',
    category: 'preparation',
    visibleTo: 'all',
    highlight: false,
  },

  // Cérémonie
  {
    time: '13:30',
    duration: '30 min',
    title: 'Démarrage cérémonie civile',
    who: 'Officier d\'état civil',
    location: 'Mairie',
    note: 'Cortège : garçons d\'honneur, demoiselles, filles d\'honneur, mariés.',
    category: 'mairie',
    visibleTo: 'all',
    highlight: true,
  },
  {
    time: '14:00',
    duration: '10 min',
    title: 'Photos devant la mairie + bulles',
    who: 'Studio Lumen',
    location: 'Devant la mairie',
    category: 'mairie',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '14:00',
    duration: '1 h',
    title: 'Séance photo de couple',
    who: 'Studio Lumen',
    location: 'Allée des palmiers',
    note: 'Lumière idéale jusqu\'à 15h15.',
    category: 'eglise',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '14:30',
    duration: '45 min',
    title: 'Démarrage cérémonie religieuse',
    who: 'Officiant',
    location: 'Église',
    note: 'Entrée de la mariée au signal de la musique.',
    category: 'eglise',
    visibleTo: 'all',
    highlight: true,
  },
  {
    time: '15:00',
    duration: '30 min',
    title: 'Accueil des invités',
    who: 'Placiers',
    location: 'Cour d\'honneur',
    category: 'eglise',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '15:15',
    duration: '20 min',
    title: 'Photos de groupe',
    who: 'Studio Lumen',
    location: 'Escalier d\'honneur',
    category: 'eglise',
    visibleTo: 'all',
    highlight: false,
  },

  // Vin d'honneur
  {
    time: '16:45',
    duration: '1 h 15',
    title: 'Cocktail',
    who: 'Table Céleste',
    location: 'Terrasse ouest',
    category: 'vindhonneur',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '17:15',
    duration: '15 min',
    title: 'Animation bouquet de la mariée',
    who: 'DJ Kévin',
    location: 'Terrasse ouest',
    category: 'vindhonneur',
    visibleTo: 'all',
    highlight: false,
  },

  // Dîner
  {
    time: '18:00',
    duration: '15 min',
    title: 'Entrée des mariés',
    who: 'DJ Kévin',
    location: 'Salle d\'honneur',
    category: 'repas',
    visibleTo: 'all',
    highlight: true,
  },
  {
    time: '18:15',
    duration: '45 min',
    title: 'Discours et remerciements',
    who: 'Témoins',
    location: 'Salle d\'honneur',
    category: 'repas',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '18:45',
    duration: '2 h',
    title: 'Dîner assis',
    who: 'Table Céleste',
    location: 'Salle d\'honneur',
    note: 'Service en trois vagues.',
    category: 'repas',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '20:30',
    duration: '20 min',
    title: 'Gâteau et dessert',
    who: 'Maison Sucré',
    location: 'Salle d\'honneur',
    category: 'repas',
    visibleTo: 'all',
    highlight: false,
  },

  // Soirée
  {
    time: '21:00',
    duration: '10 min',
    title: 'Première danse',
    who: 'DJ Kévin',
    location: 'Piste',
    category: 'bal',
    visibleTo: 'all',
    highlight: true,
  },
  {
    time: '21:15',
    duration: '4 h',
    title: 'Ouverture du bal',
    who: 'DJ Kévin',
    location: 'Piste',
    category: 'bal',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '22:00',
    duration: '20 min',
    title: 'Feu d\'artifice',
    who: 'Prestataire pyro',
    location: 'Pelouse nord',
    note: 'Autorisation préfectorale à vérifier.',
    category: 'bal',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '23:30',
    duration: '30 min',
    title: 'Bar de nuit',
    who: 'Table Céleste',
    location: 'Terrasse ouest',
    category: 'bal',
    visibleTo: 'all',
    highlight: false,
  },
  {
    time: '01:00',
    duration: '1 h',
    title: 'Départ des invités',
    who: 'Navettes',
    location: 'Cour d\'honneur',
    category: 'bal',
    visibleTo: 'vendors',
    highlight: false,
  },
];
